[package]
name = "soccer"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
chrono-tz = "0.10.0"
colored = "2.1.0"
prettytable = "0.10.0"
regex = "1.11.0"
reqwest = "0.12.7"
scraper = "0.20.0"
serde_json = "1.0.128"
tokio = {version = "^1.40.0", features = ["full"]}
